#!/usr/bin/env bash
# Deploy page_html_heavy_*.html pages to the web server.
#
# What this script does:
#   1. rsync the 10 heavy HTML pages to root@204.168.163.45:/var/www/html/
#   2. Write an nginx conf.d snippet that sets Cache-Control: no-cache for these pages
#   3. Reload nginx
#   4. Add the 10 URLs to config/urls.txt (idempotent — skips if already present)
#   5. Test each URL: curl from the web server itself, verify HTTP 200 and >5KB body

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PAGES_DIR="$REPO_ROOT/webserver/pages"
URLS_FILE="$REPO_ROOT/config/urls.txt"

WEB_SERVER="root@204.168.163.45"
WEB_ROOT="/var/www/html"
SSH_KEY="$HOME/.ssh/nico-thesis"
SSH_OPTS="-i $SSH_KEY -o StrictHostKeyChecking=no -o ConnectTimeout=10"

NGINX_SNIPPET_PATH="/etc/nginx/conf.d/heavy-pages-no-cache.conf"

echo "======================================================================"
echo "  deploy_heavy_html.sh"
echo "======================================================================"

# ── Step 1: rsync HTML pages ───────────────────────────────────────────────
echo
echo "[1/5] Syncing page_html_heavy_*.html to ${WEB_SERVER}:${WEB_ROOT}/"
rsync -avz --progress \
    -e "ssh $SSH_OPTS" \
    "$PAGES_DIR"/page_html_heavy_*.html \
    "${WEB_SERVER}:${WEB_ROOT}/"
echo "  rsync done."

# ── Step 2: Write nginx no-cache snippet ──────────────────────────────────
echo
echo "[2/5] Writing nginx cache-control snippet to ${NGINX_SNIPPET_PATH}"

NGINX_CONF='# Auto-generated by deploy_heavy_html.sh — do not edit by hand.
# Forces no-cache for heavy HTML research pages so the browser always fetches
# fresh content and all sub-resources, giving consistent packet counts.
server {
    listen 80;
    server_name _;

    location ~* ^/page_html_heavy_[0-9]+\.html$ {
        root /var/www/html;
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
    }
}'

ssh $SSH_OPTS "$WEB_SERVER" "cat > ${NGINX_SNIPPET_PATH}" <<EOF
$NGINX_CONF
EOF
echo "  nginx snippet written."

# ── Step 3: Test nginx config and reload ──────────────────────────────────
echo
echo "[3/5] Testing nginx configuration and reloading"
ssh $SSH_OPTS "$WEB_SERVER" "nginx -t && systemctl reload nginx"
echo "  nginx reloaded successfully."

# ── Step 4: Add URLs to config/urls.txt (idempotent) ─────────────────────
echo
echo "[4/5] Adding page_html_heavy_*.html to $URLS_FILE"
added=0
for i in $(seq 1 10); do
    entry="page_html_heavy_${i}.html"
    if grep -qxF "$entry" "$URLS_FILE" 2>/dev/null; then
        echo "  already present: $entry"
    else
        echo "$entry" >> "$URLS_FILE"
        echo "  added: $entry"
        added=$((added + 1))
    fi
done
echo "  $added new URL(s) added to $URLS_FILE."

# ── Step 5: Test each URL ─────────────────────────────────────────────────
echo
echo "[5/5] Testing each URL (curl from web server, expect HTTP 200 and >5120 bytes)"
echo

all_ok=true
for i in $(seq 1 10); do
    url="http://localhost/page_html_heavy_${i}.html"
    result=$(ssh $SSH_OPTS "$WEB_SERVER" \
        "curl -s -o /tmp/_heavy_test.html -w '%{http_code} %{size_download}' '${url}'" 2>&1)
    http_code=$(echo "$result" | awk '{print $1}')
    size=$(echo "$result" | awk '{print $2}')

    if [[ "$http_code" == "200" && "$size" -gt 5120 ]]; then
        printf "  ✓ page_html_heavy_%02d.html  HTTP %s  %s bytes\n" "$i" "$http_code" "$size"
    else
        printf "  ✗ page_html_heavy_%02d.html  HTTP %s  %s bytes  FAIL\n" "$i" "$http_code" "$size"
        all_ok=false
    fi
done

echo
if $all_ok; then
    echo "======================================================================"
    echo "  All 10 pages deployed and verified successfully."
    echo "======================================================================"
else
    echo "======================================================================"
    echo "  WARNING: One or more pages failed the HTTP/size check."
    echo "  SSH into ${WEB_SERVER} and check nginx error logs:"
    echo "    journalctl -u nginx -n 50"
    echo "    ls -lh ${WEB_ROOT}/page_html_heavy_*.html"
    echo "======================================================================"
    exit 1
fi
